### PR TITLE
handle \r\n style line-ends of windows .sql files

### PR DESCRIPTION
**Pull request by tschnibo**
#8

Here my first PR. Don't hesitate to critisize! Best Tschnibo

### CODE REVIEW

**Comment by tschnibo** [comment]
Oh, now I already added a second commit, much too early... and not on the same topic.
I was looking at how to add a "custom driver" option....
I'll try to branch that out or remove that commit again somehow :)

Nevertheless I would be interested in if you would be willing to put such a "custom driver" option...

**Comment by tschnibo** [comment]
Uff... sorry for the mess! The first commit is the relevant one... if you want to reject the others, this would be maybe easier. I just don't get the hang out of git yet...

**Review by lpil — COMMENTED** [review]
This looks great! Thank you!

Not to worry about the git stuff, I can do a squash merge to tidy it up.

I am worried that I might accidentally open the new SQL file on Linux and change the line endings. Could you make the new test also read the file and assert that it contains `\r\n`? That will catch it if I do make this mistake.

**Comment by tschnibo** [comment]
Thank you for your feedback! 

Oh, yes, good point! 

I even produced the file on linux, but I guess otherwise this would be up to the used editor. 

I added to the test accordingly.

**Review by lpil — APPROVED** [review]
Wonderful, thank you!

**Pull request merged**
